name: model-supervisé RL
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Your ML workflow goes here
          pip install -r requirements.txt
          python 01_prod_regression_ci__tutorial.py
          # Write your CML report
          echo "## Metriques:" >> report.md
          cat metrics.txt >> report.md
          
          #Ajouter à la fin de votre fichier yaml ces instructions afin de recuperer les fichiers
          git config --global user.email "kar.saoud@gmail.com"
          git config --global user.name "MagicSardine"
          git add report.md metrics.txt
          git commit -m "pousser vers github repository"
          git push origin HEAD:master
